ALTER TABLE TB001_USUARIO
    ADD COLUMN BOL_ATIVO BOOLEAN;

UPDATE TB001_USUARIO
SET BOL_ATIVO = (STR_STATUS = 'ATIVO');

ALTER TABLE TB001_USUARIO
    ALTER COLUMN BOL_ATIVO SET DEFAULT TRUE,
    ALTER COLUMN BOL_ATIVO SET NOT NULL;

ALTER TABLE TB001_USUARIO
    DROP CONSTRAINT CK001_01_STATUS,
    DROP COLUMN STR_STATUS;
